module.exports = {
    1: {
        id: 1,
        type: 3,
        name: '新手木剑',
        price: 1000,
        unit: 'tael',
        career: 0,
        level: 1,
        pos: 1,
        attr: 5,
        tips: '制作比较粗糙的木剑,佩戴后可提升些许攻击。'
    },
    2: {
        id: 2,
        type: 3,
        name: '新手头巾',
        price: 1000,
        unit: 'tael',
        career: 0,
        level: 1,
        pos: 2,
        attr: 5,
        tips: '制作比较粗糙的头巾,佩戴后可提升些许法力。'
    },
    3: {
        id: 3,
        type: 3,
        name: '新手布衣',
        price: 1000,
        unit: 'tael',
        career: 0,
        level: 1,
        pos: 3,
        attr: 5,
        tips: '制作比较粗糙的布衣,佩戴后可提升些许生命。'
    },
    4: {
        id: 4,
        type: 3,
        name: '新手腰带',
        price: 1000,
        unit: 'tael',
        career: 0,
        level: 1,
        pos: 4,
        attr: 5,
        tips: '制作比较粗糙的腰带,佩戴后可提升些许防御。'
    },
    5: {
        id: 5,
        type: 3,
        name: '新手草鞋',
        price: 1000,
        unit: 'tael',
        career: 0,
        level: 1,
        pos: 5,
        attr: 5,
        tips: '制作比较粗糙的草鞋,佩戴后可提升些许闪避。'
    },
    6: {
        id: 6,
        type: 3,
        name: '紫金剑',
        price: 5000,
        unit: 'tael',
        career: 0,
        level: 10,
        pos: 1,
        attr: 2,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的神剑。'
    },
    7: {
        id: 7,
        type: 3,
        name: '紫金盔',
        price: 5000,
        unit: 'tael',
        career: 0,
        level: 10,
        pos: 2,
        attr: 2,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的战盔。'
    },
    8: {
        id: 8,
        type: 3,
        name: '紫金甲',
        price: 5000,
        unit: 'tael',
        career: 0,
        level: 10,
        pos: 3,
        attr: 2,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的战甲。'
    },
    9: {
        id: 9,
        type: 3,
        name: '紫金带',
        price: 5000,
        unit: 'tael',
        career: 0,
        level: 10,
        pos: 4,
        attr: 2,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的腰带。'
    },
    10: {
        id: 10,
        type: 3,
        name: '紫金靴',
        price: 5000,
        unit: 'tael',
        career: 0,
        level: 10,
        pos: 5,
        attr: 2,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的战靴。'
    },
    11: {
        id: 11,
        type: 3,
        name: '皇极法杖',
        price: 20000,
        unit: 'tael',
        career: 1,
        level: 20,
        pos: 1,
        attr: 1,
        group: 10002,
        tips: '五大皇极套装之一,吸收天地煞气而成,蕴含了毁天灭地的力量。'
    },
    12: {
        id: 12,
        type: 3,
        name: '皇极头巾',
        price: 20000,
        unit: 'tael',
        career: 1,
        level: 20,
        pos: 2,
        attr: 1,
        group: 10002,
        tips: '五大皇极套装之一,吸收天地煞气而成,蕴含了源源不断的法力。'
    },
    13: {
        id: 13,
        type: 3,
        name: '皇极法袍',
        price: 20000,
        unit: 'tael',
        career: 1,
        level: 20,
        pos: 3,
        attr: 1,
        group: 10002,
        tips: '五大皇极套装之一,吸收天地煞气而成,蕴含了无穷无尽的生机。'
    },
    14: {
        id: 14,
        type: 3,
        name: '皇极束带',
        price: 20000,
        unit: 'tael',
        career: 1,
        level: 20,
        pos: 4,
        attr: 1,
        group: 10002,
        tips: '五大皇极套装之一,吸收天地煞气而成,拥有极为恐怖的防御。'
    },
    15: {
        id: 15,
        type: 3,
        name: '皇极布鞋',
        price: 20000,
        unit: 'tael',
        career: 1,
        level: 20,
        pos: 5,
        attr: 1,
        group: 10002,
        tips: '五大皇极套装之一,吸收天地煞气而成,拥有鬼魅般的速度。'
    },
    16: {
        id: 16,
        type: 3,
        name: '皇鼎长枪',
        price: 20000,
        unit: 'tael',
        career: 2,
        level: 20,
        pos: 1,
        attr: 1,
        group: 10003,
        tips: '五大皇鼎套装之一,吸收天地煞气而成,蕴含了毁天灭地的力量。'
    },
    17: {
        id: 17,
        type: 3,
        name: '皇鼎头盔',
        price: 20000,
        unit: 'tael',
        career: 2,
        level: 20,
        pos: 2,
        attr: 1,
        group: 10003,
        tips: '五大皇鼎装之一,吸收天地煞气而成,蕴含了源源不断的法力。'
    },
    18: {
        id: 18,
        type: 3,
        name: '皇鼎战恺',
        price: 20000,
        unit: 'tael',
        career: 2,
        level: 20,
        pos: 3,
        attr: 1,
        group: 10003,
        tips: '五大皇鼎套装之一,吸收天地煞气而成,蕴含了无穷无尽的生机。'
    },
    19: {
        id: 19,
        type: 3,
        name: '皇鼎腰带',
        price: 20000,
        unit: 'tael',
        career: 2,
        level: 20,
        pos: 4,
        attr: 1,
        group: 10003,
        tips: '五大皇鼎套装之一,吸收天地煞气而成,拥有极为恐怖的防御。'
    },
    20: {
        id: 20,
        type: 3,
        name: '皇鼎战靴',
        price: 20000,
        unit: 'tael',
        career: 2,
        level: 20,
        pos: 5,
        attr: 1,
        group: 10003,
        tips: '五大皇鼎套装之一,吸收天地煞气而成,拥有鬼魅般的速度。'
    },
    21: {
        id: 21,
        type: 3,
        name: '皇泽长弓',
        price: 20000,
        unit: 'tael',
        career: 3,
        level: 20,
        pos: 1,
        attr: 1,
        group: 10004,
        tips: '五大皇泽套装之一,吸收天地煞气而成,蕴含了毁天灭地的力量。'
    },
    22: {
        id: 22,
        type: 3,
        name: '皇泽头巾',
        price: 20000,
        unit: 'tael',
        career: 3,
        level: 20,
        pos: 2,
        attr: 1,
        group: 10004,
        tips: '五大皇泽装之一,吸收天地煞气而成,蕴含了源源不断的法力。'
    },
    23: {
        id: 23,
        type: 3,
        name: '皇泽皮衣',
        price: 20000,
        unit: 'tael',
        career: 3,
        level: 20,
        pos: 3,
        attr: 1,
        group: 10004,
        tips: '五大皇泽套装之一,吸收天地煞气而成,蕴含了无穷无尽的生机。'
    },
    24: {
        id: 24,
        type: 3,
        name: '皇泽腰带',
        price: 20000,
        unit: 'tael',
        career: 3,
        level: 20,
        pos: 4,
        attr: 1,
        group: 10004,
        tips: '五大皇泽套装之一,吸收天地煞气而成,拥有极为恐怖的防御。'
    },
    25: {
        id: 25,
        type: 3,
        name: '皇泽长靴',
        price: 20000,
        unit: 'tael',
        career: 3,
        level: 20,
        pos: 5,
        attr: 1,
        group: 10004,
        tips: '五大皇泽套装之一,吸收天地煞气而成,拥有鬼魅般的速度。'
    },
    26: {
        id: 26,
        type: 3,
        name: '星辰法杖',
        career: 1,
        level: 35,
        pos: 1,
        attr: 2,
        group: 10005,
        tips: '耗费无数武器晶石与世界声望锻造而成的武器,唯有强者才配拥有。',
        make: {
            article: '118-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    27: {
        id: 27,
        type: 3,
        name: '星辰头巾',
        career: 1,
        level: 35,
        pos: 2,
        attr: 2,
        group: 10005,
        tips: '耗费无数头盔晶石与世界声望锻造而成的头巾,唯有强者才配拥有。',
        make: {
            article: '122-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    28: {
        id: 28,
        type: 3,
        name: '星辰法袍',
        career: 1,
        level: 35,
        pos: 3,
        attr: 2,
        group: 10005,
        tips: '耗费无数铠甲晶石与世界声望锻造而成的法袍,唯有强者才配拥有。',
        make: {
            article: '126-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    29: {
        id: 29,
        type: 3,
        name: '星辰束带',
        career: 1,
        level: 35,
        pos: 4,
        attr: 2,
        group: 10005,
        tips: '耗费无数腰带晶石与世界声望锻造而成的束带,唯有强者才配拥有。',
        make: {
            article: '130-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    30: {
        id: 30,
        type: 3,
        name: '星辰布鞋',
        career: 1,
        level: 35,
        pos: 5,
        attr: 2,
        group: 10005,
        tips: '耗费无数鞋子晶石与世界声望锻造而成的布鞋,唯有强者才配拥有。',
        make: {
            article: '134-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    31: {
        id: 31,
        type: 3,
        name: '玉尊战戟',
        career: 2,
        level: 35,
        pos: 1,
        attr: 2,
        group: 10006,
        tips: '耗费无数武器晶石与世界声望锻造而成的武器,唯有强者才配拥有。',
        make: {
            article: '118-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    32: {
        id: 32,
        type: 3,
        name: '玉尊战盔',
        career: 2,
        level: 35,
        pos: 2,
        attr: 2,
        group: 10006,
        tips: '耗费无数头盔晶石与世界声望锻造而成的头盔,唯有强者才配拥有。',
        make: {
            article: '122-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    33: {
        id: 33,
        type: 3,
        name: '玉尊战甲',
        career: 2,
        level: 35,
        pos: 3,
        attr: 2,
        group: 10006,
        tips: '耗费无数盔甲晶石与世界声望锻造而成的盔甲,唯有强者才配拥有。',
        make: {
            article: '126-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    34: {
        id: 34,
        type: 3,
        name: '玉尊战带',
        career: 2,
        level: 35,
        pos: 4,
        attr: 2,
        group: 10006,
        tips: '耗费无数腰带晶石与世界声望锻造而成的腰带,唯有强者才配拥有。',
        make: {
            article: '130-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    35: {
        id: 35,
        type: 3,
        name: '玉尊战靴',
        career: 2,
        level: 35,
        pos: 5,
        attr: 2,
        group: 10006,
        tips: '耗费无数鞋子晶石与世界声望锻造而成的鞋子,唯有强者才配拥有。',
        make: {
            article: '134-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    36: {
        id: 36,
        type: 3,
        name: '凌影长剑',
        career: 3,
        level: 35,
        pos: 1,
        attr: 2,
        group: 10007,
        tips: '耗费无数武器晶石与世界声望锻造而成的武器,唯有强者才配拥有。',
        make: {
            article: '118-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    37: {
        id: 37,
        type: 3,
        name: '凌影头巾',
        career: 3,
        level: 35,
        pos: 2,
        attr: 2,
        group: 10007,
        tips: '耗费无数头盔晶石与世界声望锻造而成的头盔,唯有强者才配拥有。',
        make: {
            article: '122-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    38: {
        id: 38,
        type: 3,
        name: '凌影长衣',
        career: 3,
        level: 35,
        pos: 3,
        attr: 2,
        group: 10007,
        tips: '耗费无数铠甲晶石与世界声望锻造而成的铠甲,唯有强者才配拥有。',
        make: {
            article: '126-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    39: {
        id: 39,
        type: 3,
        name: '凌影玉束',
        career: 3,
        level: 35,
        pos: 4,
        attr: 2,
        group: 10007,
        tips: '耗费无数腰带晶石与世界声望锻造而成的腰带,唯有强者才配拥有。',
        make: {
            article: '130-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    40: {
        id: 40,
        type: 3,
        name: '凌影布鞋',
        career: 3,
        level: 35,
        pos: 5,
        attr: 2,
        group: 10007,
        tips: '耗费无数鞋子晶石与世界声望锻造而成的鞋子,唯有强者才配拥有。',
        make: {
            article: '134-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    41: {
        id: 41,
        type: 3,
        name: '飞炼法杖',
        career: 1,
        level: 55,
        pos: 1,
        attr: 3,
        group: 10008,
        tips: '传说中的飞炼套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '119-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    42: {
        id: 42,
        type: 3,
        name: '飞炼头巾',
        career: 1,
        level: 55,
        pos: 2,
        attr: 3,
        group: 10008,
        tips: '传说中的飞炼套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '123-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    43: {
        id: 43,
        type: 3,
        name: '飞炼法袍',
        career: 1,
        level: 55,
        pos: 3,
        attr: 3,
        group: 10008,
        tips: '传说中的飞炼套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '127-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    44: {
        id: 44,
        type: 3,
        name: '飞炼束带',
        career: 1,
        level: 55,
        pos: 4,
        attr: 3,
        group: 10008,
        tips: '传说中的飞炼套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '131-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    45: {
        id: 45,
        type: 3,
        name: '飞炼布鞋',
        career: 1,
        level: 55,
        pos: 5,
        attr: 3,
        group: 10008,
        tips: '传说中的飞炼套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '135-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    46: {
        id: 46,
        type: 3,
        name: '飞尊战戟',
        career: 2,
        level: 55,
        pos: 1,
        attr: 3,
        group: 10009,
        tips: '传说中的飞尊套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '119-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    47: {
        id: 47,
        type: 3,
        name: '飞尊战盔',
        career: 2,
        level: 55,
        pos: 2,
        attr: 3,
        group: 10009,
        tips: '传说中的飞尊套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '123-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    48: {
        id: 48,
        type: 3,
        name: '飞尊战甲',
        career: 2,
        level: 55,
        pos: 3,
        attr: 3,
        group: 10009,
        tips: '传说中的飞尊套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '127-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    49: {
        id: 49,
        type: 3,
        name: '飞尊战带',
        career: 2,
        level: 55,
        pos: 4,
        attr: 3,
        group: 10009,
        tips: '传说中的飞尊套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '131-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    50: {
        id: 50,
        type: 3,
        name: '飞尊战靴',
        career: 2,
        level: 55,
        pos: 5,
        attr: 3,
        group: 10009,
        tips: '传说中的飞尊套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '135-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    51: {
        id: 51,
        type: 3,
        name: '飞影长剑',
        career: 3,
        level: 55,
        pos: 1,
        attr: 3,
        group: 10010,
        tips: '传说中的飞影套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '119-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    52: {
        id: 52,
        type: 3,
        name: '飞影头巾',
        career: 3,
        level: 55,
        pos: 2,
        attr: 3,
        group: 10010,
        tips: '传说中的飞影套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '123-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    53: {
        id: 53,
        type: 3,
        name: '飞影长衣',
        career: 3,
        level: 55,
        pos: 3,
        attr: 3,
        group: 10010,
        tips: '传说中的飞影套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '127-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    54: {
        id: 54,
        type: 3,
        name: '飞影玉束',
        career: 3,
        level: 55,
        pos: 4,
        attr: 3,
        group: 10010,
        tips: '传说中的飞影套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '131-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    55: {
        id: 55,
        type: 3,
        name: '飞影布鞋',
        career: 3,
        level: 55,
        pos: 5,
        attr: 3,
        group: 10010,
        tips: '传说中的飞影套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '135-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    56: {
        id: 56,
        type: 3,
        name: '金光法杖',
        career: 1,
        level: 70,
        pos: 1,
        attr: 4,
        group: 10011,
        tips: '70级金光套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '120-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    57: {
        id: 57,
        type: 3,
        name: '金光头巾',
        career: 1,
        level: 70,
        pos: 2,
        attr: 4,
        group: 10011,
        tips: '70级金光套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '124-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    58: {
        id: 58,
        type: 3,
        name: '金光法袍',
        career: 1,
        level: 70,
        pos: 3,
        attr: 4,
        group: 10011,
        tips: '70级金光套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '128-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    59: {
        id: 59,
        type: 3,
        name: '金光束带',
        career: 1,
        level: 70,
        pos: 4,
        attr: 4,
        group: 10011,
        tips: '70级金光套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '132-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    60: {
        id: 60,
        type: 3,
        name: '金光布鞋',
        career: 1,
        level: 70,
        pos: 5,
        attr: 4,
        group: 10011,
        tips: '70级金光套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '136-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    61: {
        id: 61,
        type: 3,
        name: '金玉战戟',
        career: 2,
        level: 70,
        pos: 1,
        attr: 4,
        group: 10012,
        tips: '70级金玉套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '120-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    62: {
        id: 62,
        type: 3,
        name: '金玉战盔',
        career: 2,
        level: 70,
        pos: 2,
        attr: 4,
        group: 10012,
        tips: '70级金玉套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '124-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    63: {
        id: 63,
        type: 3,
        name: '金玉战甲',
        career: 2,
        level: 70,
        pos: 3,
        attr: 4,
        group: 10012,
        tips: '70级金玉套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '128-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    64: {
        id: 64,
        type: 3,
        name: '金玉战带',
        career: 2,
        level: 70,
        pos: 4,
        attr: 4,
        group: 10012,
        tips: '70级金玉套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '132-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    65: {
        id: 65,
        type: 3,
        name: '金玉战靴',
        career: 2,
        level: 70,
        pos: 5,
        attr: 4,
        group: 10012,
        tips: '70级金玉套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '136-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    66: {
        id: 66,
        type: 3,
        name: '金流长剑',
        career: 3,
        level: 70,
        pos: 1,
        attr: 4,
        group: 10013,
        tips: '70级金流套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '120-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    67: {
        id: 67,
        type: 3,
        name: '金流头巾',
        career: 3,
        level: 70,
        pos: 2,
        attr: 4,
        group: 10013,
        tips: '70级金流套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '124-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    68: {
        id: 68,
        type: 3,
        name: '金流长衣',
        career: 3,
        level: 70,
        pos: 3,
        attr: 4,
        group: 10013,
        tips: '70级金流套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '128-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    69: {
        id: 69,
        type: 3,
        name: '金流玉束',
        career: 3,
        level: 70,
        pos: 4,
        attr: 4,
        group: 10013,
        tips: '70级金流套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '132-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    70: {
        id: 70,
        type: 3,
        name: '金流布鞋',
        career: 3,
        level: 70,
        pos: 5,
        attr: 4,
        group: 10013,
        tips: '70级金流套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '136-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    71: {
        id: 71,
        type: 3,
        name: '无极の法杖',
        career: 1,
        level: 80,
        pos: 1,
        attr: 5,
        group: 10014,
        tips: '顶级声望套装,无极套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '121-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    72: {
        id: 72,
        type: 3,
        name: '无极の头巾',
        career: 1,
        level: 80,
        pos: 2,
        attr: 5,
        group: 10014,
        tips: '顶级声望套装,无极套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '125-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    73: {
        id: 73,
        type: 3,
        name: '无极の法袍',
        career: 1,
        level: 80,
        pos: 3,
        attr: 5,
        group: 10014,
        tips: '顶级声望套装,无极套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '129-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    74: {
        id: 74,
        type: 3,
        name: '无极の束带',
        career: 1,
        level: 80,
        pos: 4,
        attr: 5,
        group: 10014,
        tips: '顶级声望套装,无极套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '125-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    75: {
        id: 75,
        type: 3,
        name: '无极の布鞋',
        career: 1,
        level: 80,
        pos: 5,
        attr: 5,
        group: 10014,
        tips: '顶级声望套装,无极套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '129-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    76: {
        id: 76,
        type: 3,
        name: '守元の战戟',
        career: 2,
        level: 80,
        pos: 1,
        attr: 5,
        group: 10015,
        tips: '顶级声望套装,守元套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '121-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    77: {
        id: 77,
        type: 3,
        name: '守元の战盔',
        career: 2,
        level: 80,
        pos: 2,
        attr: 5,
        group: 10015,
        tips: '顶级声望套装,守元套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '125-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    78: {
        id: 78,
        type: 3,
        name: '守元の战甲',
        career: 2,
        level: 80,
        pos: 3,
        attr: 5,
        group: 10015,
        tips: '顶级声望套装,守元套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '129-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    79: {
        id: 79,
        type: 3,
        name: '守元の战带',
        career: 2,
        level: 80,
        pos: 4,
        attr: 5,
        group: 10015,
        tips: '顶级声望套装,守元套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '133-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    80: {
        id: 80,
        type: 3,
        name: '守元の战靴',
        career: 2,
        level: 80,
        pos: 5,
        attr: 5,
        group: 10015,
        tips: '顶级声望套装,守元套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '137-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    81: {
        id: 81,
        type: 3,
        name: '遁一の长剑',
        career: 3,
        level: 80,
        pos: 1,
        attr: 5,
        group: 10016,
        tips: '顶级声望套装,遁一套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '121-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    82: {
        id: 82,
        type: 3,
        name: '遁一の头巾',
        career: 3,
        level: 80,
        pos: 2,
        attr: 5,
        group: 10016,
        tips: '顶级声望套装,遁一套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '125-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    83: {
        id: 83,
        type: 3,
        name: '遁一の长衣',
        career: 3,
        level: 80,
        pos: 3,
        attr: 5,
        group: 10016,
        tips: '顶级声望套装,遁一套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '129-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    84: {
        id: 84,
        type: 3,
        name: '遁一の玉束',
        career: 3,
        level: 80,
        pos: 4,
        attr: 5,
        group: 10016,
        tips: '顶级声望套装,遁一套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '133-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    85: {
        id: 85,
        type: 3,
        name: '遁一の布鞋',
        career: 3,
        level: 80,
        pos: 5,
        attr: 5,
        group: 10016,
        tips: '顶级声望套装,遁一套装之一,每个部位都有强大的力量,集齐五件套即可获得大量属性加成。',
        make: {
            article: '137-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    86: {
        id: 86,
        type: 3,
        name: '生死の法杖',
        career: 1,
        level: 90,
        pos: 1,
        attr: 7,
        group: 10017,
        tips: '借天地法则铸造的生死套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握生死之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    87: {
        id: 87,
        type: 3,
        name: '生死の头巾',
        career: 1,
        level: 90,
        pos: 2,
        attr: 7,
        group: 10017,
        tips: '借天地法则铸造的生死套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握生死之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    88: {
        id: 88,
        type: 3,
        name: '生死の法袍',
        career: 1,
        level: 90,
        pos: 3,
        attr: 7,
        group: 10017,
        tips: '借天地法则铸造的生死套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握生死之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    89: {
        id: 89,
        type: 3,
        name: '生死の束带',
        career: 1,
        level: 90,
        pos: 4,
        attr: 7,
        group: 10017,
        tips: '借天地法则铸造的生死套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握生死之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    90: {
        id: 90,
        type: 3,
        name: '生死の布鞋',
        career: 1,
        level: 90,
        pos: 5,
        attr: 7,
        group: 10017,
        tips: '借天地法则铸造的生死套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握生死之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    91: {
        id: 91,
        type: 3,
        name: '永恒の战戟',
        career: 2,
        level: 90,
        pos: 1,
        attr: 7,
        group: 10018,
        tips: '借天地法则铸造的永恒套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握永恒之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    92: {
        id: 92,
        type: 3,
        name: '永恒の战盔',
        career: 2,
        level: 90,
        pos: 2,
        attr: 7,
        group: 10018,
        tips: '借天地法则铸造的永恒套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握永恒之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    93: {
        id: 93,
        type: 3,
        name: '永恒の战甲',
        career: 2,
        level: 90,
        pos: 3,
        attr: 7,
        group: 10018,
        tips: '借天地法则铸造的永恒套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握永恒之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    94: {
        id: 94,
        type: 3,
        name: '永恒の战带',
        career: 2,
        level: 90,
        pos: 4,
        attr: 7,
        group: 10018,
        tips: '借天地法则铸造的永恒套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握永恒之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    95: {
        id: 95,
        type: 3,
        name: '永恒の战靴',
        career: 2,
        level: 90,
        pos: 5,
        attr: 7,
        group: 10018,
        tips: '借天地法则铸造的永恒套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握永恒之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    96: {
        id: 96,
        type: 3,
        name: '太初の古剑',
        career: 3,
        level: 90,
        pos: 1,
        attr: 7,
        group: 10019,
        tips: '借天地法则铸造的太初套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握太初之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    97: {
        id: 97,
        type: 3,
        name: '太初の头巾',
        career: 3,
        level: 90,
        pos: 2,
        attr: 7,
        group: 10019,
        tips: '借天地法则铸造的太初套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握太初之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    98: {
        id: 98,
        type: 3,
        name: '太初の长衣',
        career: 3,
        level: 90,
        pos: 3,
        attr: 7,
        group: 10019,
        tips: '借天地法则铸造的太初套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握太初之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    99: {
        id: 99,
        type: 3,
        name: '太初の玉束',
        career: 3,
        level: 90,
        pos: 4,
        attr: 7,
        group: 10019,
        tips: '借天地法则铸造的太初套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握太初之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    100: {
        id: 100,
        type: 3,
        name: '太初の布鞋',
        career: 3,
        level: 90,
        pos: 5,
        attr: 7,
        group: 10019,
        tips: '借天地法则铸造的太初套装之一,每个部位都有强大的法则之力,据说集齐五件套者可掌握太初之道。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    101: {
        id: 101,
        type: 3,
        name: '黄泉の法杖',
        career: 1,
        level: 100,
        pos: 1,
        attr: 7,
        group: 10020,
        tips: '以黄泉大道铸造的黄泉套装之一,传说乃是太古幽冥地府的神器,拥有掌生死,握轮回的无上伟力。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    102: {
        id: 102,
        type: 3,
        name: '黄泉の头巾',
        career: 1,
        level: 100,
        pos: 2,
        attr: 7,
        group: 10020,
        tips: '以黄泉大道铸造的黄泉套装之一,传说乃是太古幽冥地府的神器,拥有掌生死,握轮回的无上伟力。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    103: {
        id: 103,
        type: 3,
        name: '黄泉の法袍',
        career: 1,
        level: 100,
        pos: 3,
        attr: 7,
        group: 10020,
        tips: '以黄泉大道铸造的黄泉套装之一,传说乃是太古幽冥地府的神器,拥有掌生死,握轮回的无上伟力。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    104: {
        id: 104,
        type: 3,
        name: '黄泉の束带',
        career: 1,
        level: 100,
        pos: 4,
        attr: 7,
        group: 10020,
        tips: '以黄泉大道铸造的黄泉套装之一,传说乃是太古幽冥地府的神器,拥有掌生死,握轮回的无上伟力。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    105: {
        id: 105,
        type: 3,
        name: '黄泉の布鞋',
        career: 1,
        level: 100,
        pos: 5,
        attr: 7,
        group: 10020,
        tips: '以黄泉大道铸造的黄泉套装之一,传说乃是太古幽冥地府的神器,拥有掌生死,握轮回的无上伟力。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    106: {
        id: 106,
        type: 3,
        name: '阴阳の战戟',
        career: 2,
        level: 100,
        pos: 1,
        attr: 7,
        group: 10021,
        tips: '以阴阳大道铸造的阴阳套装之一,传说阴阳大道的天地钟爱,以此道铸造的神器,拥有逆转阴阳的无上造化。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    107: {
        id: 107,
        type: 3,
        name: '阴阳の战盔',
        career: 2,
        level: 100,
        pos: 2,
        attr: 7,
        group: 10021,
        tips: '以阴阳大道铸造的阴阳套装之一,传说阴阳大道的天地钟爱,以此道铸造的神器,拥有逆转阴阳的无上造化。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    108: {
        id: 108,
        type: 3,
        name: '阴阳の战甲',
        career: 2,
        level: 100,
        pos: 3,
        attr: 7,
        group: 10021,
        tips: '以阴阳大道铸造的阴阳套装之一,传说阴阳大道的天地钟爱,以此道铸造的神器,拥有逆转阴阳的无上造化。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    109: {
        id: 109,
        type: 3,
        name: '阴阳の战带',
        career: 2,
        level: 100,
        pos: 4,
        attr: 7,
        group: 10021,
        tips: '以阴阳大道铸造的阴阳套装之一,传说阴阳大道的天地钟爱,以此道铸造的神器,拥有逆转阴阳的无上造化。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    110: {
        id: 110,
        type: 3,
        name: '阴阳の战靴',
        career: 2,
        level: 100,
        pos: 5,
        attr: 7,
        group: 10021,
        tips: '以阴阳大道铸造的阴阳套装之一,传说阴阳大道的天地钟爱,以此道铸造的神器,拥有逆转阴阳的无上造化。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    111: {
        id: 111,
        type: 3,
        name: '太虚の古剑',
        career: 3,
        level: 100,
        pos: 1,
        attr: 7,
        group: 10022,
        tips: '以空间大道铸造的太虚套装之一,佩戴此道所铸造的神器,可游离于虚空之中,超脱一切。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    112: {
        id: 112,
        type: 3,
        name: '太虚の头巾',
        career: 3,
        level: 100,
        pos: 2,
        attr: 7,
        group: 10022,
        tips: '以空间大道铸造的太虚套装之一,佩戴此道所铸造的神器,可游离于虚空之中,超脱一切。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    113: {
        id: 113,
        type: 3,
        name: '太虚の长衣',
        career: 3,
        level: 100,
        pos: 3,
        attr: 7,
        group: 10022,
        tips: '以空间大道铸造的太虚套装之一,佩戴此道所铸造的神器,可游离于虚空之中,超脱一切。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    114: {
        id: 114,
        type: 3,
        name: '太虚の玉束',
        career: 3,
        level: 100,
        pos: 4,
        attr: 7,
        group: 10022,
        tips: '以空间大道铸造的太虚套装之一,佩戴此道所铸造的神器,可游离于虚空之中,超脱一切。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    115: {
        id: 115,
        type: 3,
        name: '太虚の布鞋',
        career: 3,
        level: 100,
        pos: 5,
        attr: 7,
        group: 10022,
        tips: '以空间大道铸造的太虚套装之一,佩戴此道所铸造的神器,可游离于虚空之中,超脱一切。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    116: {
        id: 116,
        type: 3,
        name: '义薄云天刃',
        career: 0,
        level: 60,
        pos: 1,
        attr: 2,
        group: 10023,
        make: 3,
        tips: '60级帮会套装,需要大量的帮会声望进行锻造,拥有强大的属性增幅。',
        make: {
            article: '119-24',
            integral: 'gang-800',
            yuanbao: 2000
        },
    },
    117: {
        id: 117,
        type: 3,
        name: '义薄云天盔',
        career: 0,
        level: 60,
        pos: 2,
        attr: 2,
        group: 10023,
        make: 3,
        tips: '60级帮会套装,需要大量的帮会声望进行锻造,拥有强大的属性增幅。',
        make: {
            article: '123-24',
            integral: 'gang-800',
            yuanbao: 2000
        },
    },
    118: {
        id: 118,
        type: 3,
        name: '义薄云天甲',
        career: 0,
        level: 60,
        pos: 3,
        attr: 2,
        group: 10023,
        make: 3,
        tips: '60级帮会套装,需要大量的帮会声望进行锻造,拥有强大的属性增幅。',
        make: {
            article: '127-24',
            integral: 'gang-800',
            yuanbao: 2000
        },
    },
    119: {
        id: 119,
        type: 3,
        name: '义薄云天带',
        career: 0,
        level: 60,
        pos: 4,
        attr: 2,
        group: 10023,
        make: 3,
        tips: '60级帮会套装,需要大量的帮会声望进行锻造,拥有强大的属性增幅。',
        make: {
            article: '131-24',
            integral: 'gang-800',
            yuanbao: 2000
        },
    },
    120: {
        id: 120,
        type: 3,
        name: '义薄云天靴',
        career: 0,
        level: 60,
        pos: 5,
        attr: 2,
        group: 10023,
        make: 3,
        tips: '60级帮会套装,需要大量的帮会声望进行锻造,拥有强大的属性增幅。',
        make: {
            article: '135-24',
            integral: 'gang-800',
            yuanbao: 2000
        },
    },
    121: {
        id: 121,
        type: 3,
        name: '气吞山河枪',
        career: 0,
        level: 75,
        pos: 1,
        attr: 3,
        group: 10024,
        make: 3,
        tips: '75级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活气吞山河套。',
        make: {
            article: '120-36',
            integral: 'gang-2000',
            yuanbao: 5000
        },
    },
    122: {
        id: 122,
        type: 3,
        name: '气吞山河盔',
        career: 0,
        level: 75,
        pos: 2,
        attr: 3,
        group: 10024,
        make: 3,
        tips: '75级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活气吞山河套。',
        make: {
            article: '124-36',
            integral: 'gang-2000',
            yuanbao: 5000
        },
    },
    123: {
        id: 123,
        type: 3,
        name: '气吞山河甲',
        career: 0,
        level: 75,
        pos: 3,
        attr: 3,
        group: 10024,
        make: 3,
        tips: '75级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活气吞山河套。',
        make: {
            article: '128-36',
            integral: 'gang-2000',
            yuanbao: 5000
        },
    },
    124: {
        id: 124,
        type: 3,
        name: '气吞山河带',
        career: 0,
        level: 75,
        pos: 4,
        attr: 3,
        group: 10024,
        make: 3,
        tips: '75级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活气吞山河套。',
        make: {
            article: '132-36',
            integral: 'gang-2000',
            yuanbao: 5000
        },
    },
    125: {
        id: 125,
        type: 3,
        name: '气吞山河靴',
        career: 0,
        level: 75,
        pos: 5,
        attr: 3,
        group: 10024,
        make: 3,
        tips: '75级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活气吞山河套。',
        make: {
            article: '136-36',
            integral: 'gang-2000',
            yuanbao: 5000
        },
    },
    126: {
        id: 126,
        type: 3,
        name: '权倾天下の枪',
        career: 0,
        level: 85,
        pos: 1,
        attr: 7,
        group: 10025,
        make: 3,
        tips: '85级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活权倾天下套。',
        make: {
            article: '121-72',
            integral: 'gang-5000',
            yuanbao: 12000
        },
    },
    127: {
        id: 127,
        type: 3,
        name: '权倾天下の盔',
        career: 0,
        level: 85,
        pos: 2,
        attr: 7,
        group: 10025,
        make: 3,
        tips: '85级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活权倾天下套。',
        make: {
            article: '125-72',
            integral: 'gang-5000',
            yuanbao: 12000
        },
    },
    128: {
        id: 128,
        type: 3,
        name: '权倾天下の甲',
        career: 0,
        level: 85,
        pos: 3,
        attr: 7,
        group: 10025,
        make: 3,
        tips: '85级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活权倾天下套。',
        make: {
            article: '129-72',
            integral: 'gang-5000',
            yuanbao: 12000
        },
    },
    129: {
        id: 129,
        type: 3,
        name: '权倾天下の带',
        career: 0,
        level: 85,
        pos: 4,
        attr: 7,
        group: 10025,
        make: 3,
        tips: '85级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活权倾天下套。',
        make: {
            article: '133-72',
            integral: 'gang-5000',
            yuanbao: 12000
        },
    },
    130: {
        id: 130,
        type: 3,
        name: '权倾天下の靴',
        career: 0,
        level: 85,
        pos: 5,
        attr: 7,
        group: 10025,
        make: 3,
        tips: '85级帮会套装,需要大量的帮会声望与顶级晶石进行锻造,集齐五件可激活权倾天下套。',
        make: {
            article: '137-72',
            integral: 'gang-5000',
            yuanbao: 12000
        },
    },
    131: {
        id: 131,
        type: 3,
        name: '醉卧沙场の枪',
        career: 0,
        level: 65,
        pos: 1,
        attr: 7,
        group: 10026,
        make: 2,
        tips: '醉卧沙场君莫笑,古来征战几人回,以无数战场功勋凝聚而出的强大套装,激活后可获得大量属性加成。',
        make: {
            article: '119-24',
            integral: 'exploit-1000',
            yuanbao: 4000
        },
    },
    132: {
        id: 132,
        type: 3,
        name: '醉卧沙场の盔',
        career: 0,
        level: 65,
        pos: 2,
        attr: 7,
        group: 10026,
        make: 2,
        tips: '醉卧沙场君莫笑,古来征战几人回,以无数战场功勋凝聚而出的强大套装,激活后可获得大量属性加成。',
        make: {
            article: '123-24',
            integral: 'exploit-1000',
            yuanbao: 4000
        },
    },
    133: {
        id: 133,
        type: 3,
        name: '醉卧沙场の甲',
        career: 0,
        level: 65,
        pos: 3,
        attr: 7,
        group: 10026,
        make: 2,
        tips: '醉卧沙场君莫笑,古来征战几人回,以无数战场功勋凝聚而出的强大套装,激活后可获得大量属性加成。',
        make: {
            article: '127-24',
            integral: 'exploit-1000',
            yuanbao: 4000
        },
    },
    134: {
        id: 134,
        type: 3,
        name: '醉卧沙场の带',
        career: 0,
        level: 65,
        pos: 4,
        attr: 7,
        group: 10026,
        make: 2,
        tips: '醉卧沙场君莫笑,古来征战几人回,以无数战场功勋凝聚而出的强大套装,激活后可获得大量属性加成。',
        make: {
            article: '131-24',
            integral: 'exploit-1000',
            yuanbao: 4000
        },
    },
    135: {
        id: 135,
        type: 3,
        name: '醉卧沙场の靴',
        career: 0,
        level: 65,
        pos: 5,
        attr: 7,
        group: 10026,
        make: 2,
        tips: '醉卧沙场君莫笑,古来征战几人回,以无数战场功勋凝聚而出的强大套装,激活后可获得大量属性加成。',
        make: {
            article: '135-24',
            integral: 'exploit-1000',
            yuanbao: 4000
        },
    },
    136: {
        id: 136,
        type: 3,
        name: '天下无双の枪',
        career: 0,
        level: 80,
        pos: 1,
        attr: 10,
        group: 10027,
        make: 2,
        tips: '集无尽战场功勋打造而成的五大神器之一,持此任一件便可尽显无敌之姿,若集齐五件当成就天下至尊。',
        make: {
            article: '121-72',
            integral: 'exploit-5000',
            yuanbao: 20000
        },
    },
    137: {
        id: 137,
        type: 3,
        name: '天下无双の盔',
        career: 0,
        level: 80,
        pos: 2,
        attr: 10,
        group: 10027,
        make: 2,
        tips: '集无尽战场功勋打造而成的五大神器之一,持此任一件便可尽显无敌之姿,若集齐五件当成就天下至尊。',
        make: {
            article: '125-72',
            integral: 'exploit-5000',
            yuanbao: 20000
        },
    },
    138: {
        id: 138,
        type: 3,
        name: '天下无双の甲',
        career: 0,
        level: 80,
        pos: 3,
        attr: 10,
        group: 10027,
        make: 2,
        tips: '集无尽战场功勋打造而成的五大神器之一,持此任一件便可尽显无敌之姿,若集齐五件当成就天下至尊。',
        make: {
            article: '129-72',
            integral: 'exploit-5000',
            yuanbao: 20000
        },
    },
    139: {
        id: 139,
        type: 3,
        name: '天下无双の带',
        career: 0,
        level: 80,
        pos: 4,
        attr: 10,
        group: 10027,
        make: 2,
        tips: '集无尽战场功勋打造而成的五大神器之一,持此任一件便可尽显无敌之姿,若集齐五件当成就天下至尊。',
        make: {
            article: '133-72',
            integral: 'exploit-5000',
            yuanbao: 20000
        },
    },
    140: {
        id: 140,
        type: 3,
        name: '天下无双の靴',
        career: 0,
        level: 80,
        pos: 5,
        attr: 10,
        group: 10027,
        make: 2,
        tips: '集无尽战场功勋打造而成的五大神器之一,持此任一件便可尽显无敌之姿,若集齐五件当成就天下至尊。',
        make: {
            article: '137-72',
            integral: 'exploit-5000',
            yuanbao: 20000
        },
    },
    141: {
        id: 141,
        type: 3,
        name: '天定姻缘の杖',
        career: 0,
        level: 55,
        pos: 1,
        attr: 10,
        group: 10028,
        make: 4,
        tips: '你与对方乃是天定姻缘之人,成婚之日,就连上苍都送来了贺礼,蕴含着强大的力量。',
        make: {
            article: '311-100',
            integral: 'world-500',
            yuanbao: 3000
        },
    },
    142: {
        id: 142,
        type: 3,
        name: '天定姻缘の冠',
        career: 0,
        level: 55,
        pos: 2,
        attr: 10,
        group: 10028,
        make: 4,
        tips: '你与对方乃是天定姻缘之人,成婚之日,就连上苍都送来了贺礼,蕴含着强大的力量。',
        make: {
            article: '311-100',
            integral: 'world-500',
            yuanbao: 3000
        },
    },
    143: {
        id: 143,
        type: 3,
        name: '天定姻缘の甲',
        career: 0,
        level: 55,
        pos: 3,
        attr: 10,
        group: 10028,
        make: 4,
        tips: '你与对方乃是天定姻缘之人,成婚之日,就连上苍都送来了贺礼,蕴含着强大的力量。',
        make: {
            article: '311-100',
            integral: 'world-500',
            yuanbao: 3000
        },
    },
    144: {
        id: 144,
        type: 3,
        name: '天定姻缘の带',
        career: 0,
        level: 55,
        pos: 4,
        attr: 10,
        group: 10028,
        make: 4,
        tips: '你与对方乃是天定姻缘之人,成婚之日,就连上苍都送来了贺礼,蕴含着强大的力量。',
        make: {
            article: '311-100',
            integral: 'world-500',
            yuanbao: 3000
        },
    },
    145: {
        id: 145,
        type: 3,
        name: '天定姻缘の靴',
        career: 0,
        level: 55,
        pos: 5,
        attr: 10,
        group: 10028,
        make: 4,
        tips: '你与对方乃是天定姻缘之人,成婚之日,就连上苍都送来了贺礼,蕴含着强大的力量。',
        make: {
            article: '311-100',
            integral: 'world-500',
            yuanbao: 3000
        },
    },
    146: {
        id: 146,
        type: 3,
        name: '生死の相契の剑',
        career: 0,
        level: 70,
        pos: 1,
        attr: 10,
        group: 10029,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,在无数岁月的见证下,你们再度向彼此许下不离不弃的诺言。',
        make: {
            article: '311-200',
            integral: 'world-3000',
            yuanbao: 10000
        },
    },
    147: {
        id: 147,
        type: 3,
        name: '生死の相契の冠',
        career: 0,
        level: 70,
        pos: 2,
        attr: 10,
        group: 10029,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,在无数岁月的见证下,你们再度向彼此许下不离不弃的诺言。',
        make: {
            article: '311-200',
            integral: 'world-3000',
            yuanbao: 10000
        },
    },
    148: {
        id: 148,
        type: 3,
        name: '生死の相契の甲',
        career: 0,
        level: 70,
        pos: 3,
        attr: 10,
        group: 10029,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,在无数岁月的见证下,你们再度向彼此许下不离不弃的诺言。',
        make: {
            article: '311-200',
            integral: 'world-3000',
            yuanbao: 10000
        },
    },
    149: {
        id: 149,
        type: 3,
        name: '生死の相契の带',
        career: 0,
        level: 70,
        pos: 4,
        attr: 10,
        group: 10029,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,在无数岁月的见证下,你们再度向彼此许下不离不弃的诺言。',
        make: {
            article: '311-200',
            integral: 'world-3000',
            yuanbao: 10000
        },
    },
    150: {
        id: 150,
        type: 3,
        name: '生死の相契の靴',
        career: 0,
        level: 70,
        pos: 5,
        attr: 10,
        group: 10029,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,在无数岁月的见证下,你们再度向彼此许下不离不弃的诺言。',
        make: {
            article: '311-200',
            integral: 'world-3000',
            yuanbao: 10000
        },
    },
    151: {
        id: 151,
        type: 3,
        name: '三生三世の剑',
        career: 0,
        level: 90,
        pos: 1,
        attr: 10,
        group: 10030,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,长久陪伴之下感悟姻缘大道,当初上苍所赐之物沾染此道因果衍生出大道。',
        make: {
            article: '311-500',
            integral: 'world-10000',
            yuanbao: 48000
        },
    },
    152: {
        id: 152,
        type: 3,
        name: '三生三世の冠',
        career: 0,
        level: 90,
        pos: 2,
        attr: 10,
        group: 10030,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,长久陪伴之下感悟姻缘大道,当初上苍所赐之物沾染此道因果衍生出大道。',
        make: {
            article: '311-500',
            integral: 'world-10000',
            yuanbao: 48000
        },
    },
    153: {
        id: 153,
        type: 3,
        name: '三生三世の甲',
        career: 0,
        level: 90,
        pos: 3,
        attr: 10,
        group: 10030,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,长久陪伴之下感悟姻缘大道,当初上苍所赐之物沾染此道因果衍生出大道。',
        make: {
            article: '311-500',
            integral: 'world-10000',
            yuanbao: 48000
        },
    },
    154: {
        id: 154,
        type: 3,
        name: '三生三世の带',
        career: 0,
        level: 90,
        pos: 4,
        attr: 10,
        group: 10030,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,长久陪伴之下感悟姻缘大道,当初上苍所赐之物沾染此道因果衍生出大道。',
        make: {
            article: '311-500',
            integral: 'world-10000',
            yuanbao: 48000
        },
    },
    155: {
        id: 155,
        type: 3,
        name: '三生三世の靴',
        career: 0,
        level: 90,
        pos: 5,
        attr: 10,
        group: 10030,
        make: 4,
        tips: '你与对方乃是天地姻缘之人,长久陪伴之下感悟姻缘大道,当初上苍所赐之物沾染此道因果衍生出大道。',
        make: {
            article: '311-500',
            integral: 'world-10000',
            yuanbao: 48000
        },
    },
    156: {
        id: 156,
        type: 3,
        name: '才子佳人の剑',
        career: 0,
        level: 77,
        pos: 1,
        attr: 8,
        group: 10031,
        integral: 1314,
        tips: '77级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    157: {
        id: 157,
        type: 3,
        name: '才子佳人の冠',
        career: 0,
        level: 77,
        pos: 2,
        attr: 8,
        group: 10031,
        integral: 1314,
        tips: '77级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    158: {
        id: 158,
        type: 3,
        name: '才子佳人の甲',
        career: 0,
        level: 77,
        pos: 3,
        attr: 8,
        group: 10031,
        integral: 1314,
        tips: '77级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    159: {
        id: 159,
        type: 3,
        name: '才子佳人の带',
        career: 0,
        level: 77,
        pos: 4,
        attr: 8,
        group: 10031,
        integral: 1314,
        tips: '77级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    160: {
        id: 160,
        type: 3,
        name: '才子佳人の靴',
        career: 0,
        level: 77,
        pos: 5,
        attr: 8,
        group: 10031,
        integral: 1314,
        tips: '77级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    161: {
        id: 161,
        type: 3,
        name: '君临天下の剑',
        career: 0,
        level: 99,
        pos: 1,
        attr: 10,
        group: 10032,
        integral: 3344,
        tips: '99级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    162: {
        id: 162,
        type: 3,
        name: '君临天下の冠',
        career: 0,
        level: 99,
        pos: 2,
        attr: 10,
        group: 10032,
        integral: 3344,
        tips: '99级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    163: {
        id: 163,
        type: 3,
        name: '君临天下の甲',
        career: 0,
        level: 99,
        pos: 3,
        attr: 10,
        group: 10032,
        integral: 3344,
        tips: '99级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    164: {
        id: 164,
        type: 3,
        name: '君临天下の带',
        career: 0,
        level: 99,
        pos: 4,
        attr: 10,
        group: 10032,
        integral: 3344,
        tips: '99级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    165: {
        id: 165,
        type: 3,
        name: '君临天下の靴',
        career: 0,
        level: 99,
        pos: 5,
        attr: 10,
        group: 10032,
        integral: 3344,
        tips: '99级全职业活动套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    166: {
        id: 166,
        type: 3,
        name: '海誓山盟の戒',
        career: 0,
        level: 35,
        pos: 6,
        attr: 7,
        group: 10033,
        make: 1,
        tips: '消耗世界声望打造的35级海誓山盟首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '138-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    167: {
        id: 167,
        type: 3,
        name: '海誓山盟の项链',
        career: 0,
        level: 35,
        pos: 7,
        attr: 7,
        group: 10033,
        make: 1,
        tips: '消耗世界声望打造的35级海誓山盟首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '142-12',
            integral: 'world-300',
            yuanbao: 700
        },
    },
    168: {
        id: 168,
        type: 3,
        name: '吉祥如意の戒',
        career: 0,
        level: 55,
        pos: 6,
        attr: 5,
        group: 10034,
        make: 1,
        tips: '消耗世界声望打造的55级吉祥如意首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '139-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    169: {
        id: 169,
        type: 3,
        name: '吉祥如意の项链',
        career: 0,
        level: 55,
        pos: 7,
        attr: 5,
        group: 10034,
        make: 1,
        tips: '消耗世界声望打造的55级吉祥如意首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '143-24',
            integral: 'world-800',
            yuanbao: 1800
        },
    },
    170: {
        id: 170,
        type: 3,
        name: '造化五行の戒',
        career: 0,
        level: 70,
        pos: 6,
        attr: 5,
        group: 10035,
        make: 1,
        tips: '消耗世界声望打造的70级造化五行首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '140-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    171: {
        id: 171,
        type: 3,
        name: '造化五行の项链',
        career: 0,
        level: 70,
        pos: 7,
        attr: 5,
        group: 10035,
        make: 1,
        tips: '消耗世界声望打造的70级造化五行首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '144-36',
            integral: 'world-2000',
            yuanbao: 5000
        },
    },
    172: {
        id: 172,
        type: 3,
        name: '不死不灭の戒',
        career: 0,
        level: 70,
        pos: 6,
        attr: 10,
        group: 10036,
        make: 2,
        tips: '消耗世界功勋打造的70级不死不灭首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '140-36',
            integral: 'exploit-2000',
            yuanbao: 10000
        },
    },
    173: {
        id: 173,
        type: 3,
        name: '不死不灭の项链',
        career: 0,
        level: 70,
        pos: 7,
        attr: 10,
        group: 10036,
        make: 2,
        tips: '消耗世界功勋打造的70级不死不灭首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '144-36',
            integral: 'exploit-2000',
            yuanbao: 10000
        },
    },
    174: {
        id: 174,
        type: 3,
        name: '幽冥碧落の戒',
        career: 0,
        level: 80,
        pos: 6,
        attr: 7,
        group: 10037,
        tips: '消耗世界声望打造的80级幽冥碧落首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '141-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    175: {
        id: 175,
        type: 3,
        name: '幽冥碧落の项链',
        career: 0,
        level: 80,
        pos: 7,
        attr: 7,
        group: 10037,
        tips: '消耗世界声望打造的80级幽冥碧落首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '145-72',
            integral: 'world-5000',
            yuanbao: 12000
        },
    },
    176: {
        id: 176,
        type: 3,
        name: '诸神黄昏の戒',
        career: 0,
        level: 90,
        pos: 6,
        attr: 7,
        group: 10038,
        tips: '消耗世界声望打造的90级诸神黄昏首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    177: {
        id: 177,
        type: 3,
        name: '诸神黄昏の项链',
        career: 0,
        level: 90,
        pos: 7,
        attr: 7,
        group: 10038,
        tips: '消耗世界声望打造的90级诸神黄昏首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '309-108',
            integral: 'world-8000',
            yuanbao: 20000
        },
    },
    178: {
        id: 178,
        type: 3,
        name: '大道同源の戒',
        career: 0,
        level: 99,
        pos: 6,
        attr: 7,
        group: 10039,
        tips: '消耗世界声望打造的99级大道同源首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    179: {
        id: 179,
        type: 3,
        name: '大道同源の项链',
        career: 0,
        level: 99,
        pos: 7,
        attr: 7,
        group: 10039,
        tips: '消耗世界声望打造的99级大道同源首饰套装,激活后可获得大量属性加成。',
        make: {
            article: '310-108',
            integral: 'world-15000',
            yuanbao: 35000
        },
    },
    180: {
        id: 180,
        type: 3,
        name: '九歌の戒',
        career: 0,
        level: 50,
        pos: 6,
        attr: 10,
        group: 10040,
        integral: 199,
        tips: '50级活动首饰套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    181: {
        id: 181,
        type: 3,
        name: '断魂の项链',
        career: 0,
        level: 50,
        pos: 7,
        attr: 10,
        group: 10040,
        integral: 199,
        tips: '50级活动首饰套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    182: {
        id: 182,
        type: 3,
        name: '上善若水の戒',
        career: 0,
        level: 99,
        pos: 6,
        attr: 10,
        group: 10041,
        integral: 3344,
        tips: '99级活动首饰套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    183: {
        id: 183,
        type: 3,
        name: '上善若水の项链',
        career: 0,
        level: 99,
        pos: 7,
        attr: 10,
        group: 10041,
        integral: 3344,
        tips: '99级活动首饰套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    184: {
        id: 184,
        type: 3,
        name: '嗜血枪',
        career: 0,
        level: 66,
        pos: 8,
        attr: 10,
        group: 10042,
        customAttr: ['atk_min', 'atk_max'],
        tips: '强大的法宝,拥有极致的毁灭力量,可消耗大量世界声望锻造也可通过某些奇遇获得。',
        make: {
            integral: 'world-1000',
            yuanbao: 2400
        },
    },
    185: {
        id: 185,
        type: 3,
        name: '水月镜',
        career: 0,
        level: 66,
        pos: 9,
        attr: 10,
        group: 10042,
        customAttr: ['dfs_min', 'dfs_max'],
        tips: '强大的法宝,极致的防御力量,可消耗大量世界声望锻造也可通过某些奇遇获得。',
        make: {
            integral: 'world-1000',
            yuanbao: 2400
        },
    },
    186: {
        id: 186,
        type: 3,
        name: '破空枪[冰]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10043,
        customAttr: ['ice_atk_min', 'ice_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的冰元素伤害。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    187: {
        id: 187,
        type: 3,
        name: '破空枪[雷]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10044,
        customAttr: ['mine_atk_min', 'mine_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的雷元素伤害。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    188: {
        id: 188,
        type: 3,
        name: '破空枪[风]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10045,
        customAttr: ['wind_atk_min', 'wind_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的风元素伤害。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    189: {
        id: 189,
        type: 3,
        name: '破空枪[水]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10046,
        customAttr: ['water_atk_min', 'water_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的水元素伤害。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    190: {
        id: 190,
        type: 3,
        name: '破空枪[火]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10047,
        customAttr: ['fire_atk_min', 'fire_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的火元素伤害。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    191: {
        id: 191,
        type: 3,
        name: '鬼脸镜[冰]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10043,
        customAttr: ['ice_dfs_min', 'ice_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的冰元素防御。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    192: {
        id: 192,
        type: 3,
        name: '鬼脸镜[雷]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10044,
        customAttr: ['mine_dfs_min', 'mine_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的雷元素防御。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    193: {
        id: 193,
        type: 3,
        name: '鬼脸镜[风]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10045,
        customAttr: ['wind_dfs_min', 'wind_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的风元素防御。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    194: {
        id: 194,
        type: 3,
        name: '鬼脸镜[水]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10046,
        customAttr: ['water_dfs_min', 'water_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的水元素防御。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    195: {
        id: 195,
        type: 3,
        name: '鬼脸镜[火]',
        career: 0,
        level: 66,
        pos: 8,
        attr: 5,
        group: 10047,
        customAttr: ['fire_dfs_min', 'fire_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的火元素防御。',
        make: {
            integral: 'world-1500',
            yuanbao: 3600
        },
    },
    196: {
        id: 196,
        type: 3,
        name: '五法霹雳珠[冰]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10048,
        customAttr: ['ice_atk_min', 'ice_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的冰元素伤害。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    197: {
        id: 197,
        type: 3,
        name: '五法霹雳珠[雷]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10049,
        customAttr: ['mine_atk_min', 'mine_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的雷元素伤害。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    198: {
        id: 198,
        type: 3,
        name: '五法霹雳珠[风]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10050,
        customAttr: ['wind_atk_min', 'wind_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的风元素伤害。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    199: {
        id: 199,
        type: 3,
        name: '五法霹雳珠[水]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10051,
        customAttr: ['water_atk_min', 'water_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的水元素伤害。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    200: {
        id: 200,
        type: 3,
        name: '五法霹雳珠[火]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10052,
        customAttr: ['fire_atk_min', 'fire_atk_max'],
        tips: '强大的元素法宝,可对敌人造成大量的火元素伤害。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    201: {
        id: 201,
        type: 3,
        name: '五法乾坤袋[冰]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10048,
        customAttr: ['ice_dfs_min', 'ice_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的冰元素防御。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    202: {
        id: 202,
        type: 3,
        name: '五法乾坤袋[雷]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10049,
        customAttr: ['mine_dfs_min', 'mine_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的雷元素防御。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    203: {
        id: 203,
        type: 3,
        name: '五法乾坤袋[风]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10050,
        customAttr: ['wind_dfs_min', 'wind_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的风元素防御。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    204: {
        id: 204,
        type: 3,
        name: '五法乾坤袋[水]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10051,
        customAttr: ['water_dfs_min', 'water_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的水元素防御。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    205: {
        id: 205,
        type: 3,
        name: '五法乾坤袋[火]',
        career: 0,
        level: 75,
        pos: 8,
        attr: 7,
        group: 10052,
        customAttr: ['fire_dfs_min', 'fire_dfs_max'],
        tips: '强大的元素法宝,可对敌人造成大量的火元素防御。',
        make: {
            integral: 'world-4800',
            yuanbao: 12000
        },
    },
    206: {
        id: 206,
        type: 3,
        name: '山河社稷の图',
        career: 0,
        level: 90,
        pos: 8,
        attr: 20,
        group: 10053,
        customAttr: ['life_max', 'mana_max'],
        tips: '传说此图内有天地，滋养天人，拥有此法宝者可化生万物，法力浩荡。',
        make: {
            article: '310-180',
            integral: 'world-10000',
            yuanbao: 24000
        },
    },
    207: {
        id: 207,
        type: 3,
        name: '九纹大道の钟',
        career: 0,
        level: 90,
        pos: 8,
        attr: 20,
        group: 10053,
        customAttr: ['atk_min', 'atk_max', 'dfs_min', 'dfs_max'],
        tips: '传说此法宝先与天地诞生之前便以存在,蕴含混沌之力,完美无缺。',
        make: {
            article: '310-180',
            integral: 'world-10000',
            yuanbao: 24000
        },
    },
    208: {
        id: 208,
        type: 3,
        name: '青莲造化の盏',
        career: 0,
        level: 99,
        pos: 8,
        attr: 10,
        group: 10054,
        integral: 3344,
        customAttr: ['ice_atk_min', 'ice_atk_max', 'mine_atk_min', 'mine_atk_max', 'wind_atk_min', 'wind_atk_max', 'water_atk_min', 'water_atk_max', 'fire_atk_min', 'fire_atk_max'],
        tips: '据说乃是一株青莲所化的古灯,无人知晓其来历,神秘无比,可化万千大道。',
        make: {
            article: '310-320',
            integral: 'world-15000',
            yuanbao: 36000
        },
    },
    209: {
        id: 209,
        type: 3,
        name: '大道轮回の印',
        career: 0,
        level: 99,
        pos: 8,
        attr: 10,
        group: 10054,
        integral: 3344,
        customAttr: ['ice_dfs_min', 'ice_dfs_max', 'mine_dfs_min', 'mine_dfs_max', 'wind_dfs_min', 'wind_dfs_max', 'water_dfs_min', 'water_dfs_max', 'fire_dfs_min', 'fire_dfs_max'],
        tips: '据说持此印者,乃大道所定之人,承载了无尽因果,可包容万物。',
        make: {
            article: '310-320',
            integral: 'world-15000',
            yuanbao: 36000
        },
    },
    210: {
        id: 210,
        type: 3,
        name: '月华相思の戒',
        career: 0,
        level: 99,
        pos: 6,
        attr: 10,
        group: 10055,
        integral: 3344,
        tips: '99级活动首饰套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    211: {
        id: 211,
        type: 3,
        name: '月华相思の项链',
        career: 0,
        level: 99,
        pos: 7,
        attr: 10,
        group: 10055,
        integral: 3344,
        tips: '99级活动首饰套装,佩戴后可提供强大的属性加成,可以在神装活动内兑换成积分。'
    },
    212: {
        id: 212,
        type: 3,
        name: '玄炎戒',
        career: 0,
        level: 25,
        pos: 6,
        attr: 1,
        tips: '蕴含一缕奇异火焰的戒指，佩戴后可获得大幅度增加命中。'
    },
    213: {
        id: 213,
        type: 3,
        name: '青木镯',
        career: 0,
        level: 25,
        pos: 7,
        attr: 1,
        tips: '使用青木所铸造的手镯，佩戴后可获得极端的毁灭。'
    },
    214: {
        id: 214,
        type: 3,
        name: '紫气戒',
        career: 0,
        level: 10,
        pos: 6,
        attr: 1,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的戒指。'
    },
    215: {
        id: 215,
        type: 3,
        name: '紫气镯',
        career: 0,
        level: 10,
        pos: 7,
        attr: 1,
        tips: '每日初晨采集紫霞之气,足足七七四十九日方铸造而成的手镯。'
    },
}

// 彡 の