export type AttrType = {
  life_max: number;
  life: number;
  mana_max: number;
  mana: number;
  atk_max: number;
  atk_min: number;
  dfs_max: number;
  dfs_min: number;
  hit: number;
  dodge: number;
  sudden: number;
  ice_atk_max: number;
  ice_atk_min: number;
  ice_dfs_max: number;
  ice_dfs_min: number;
  mine_atk_max: number;
  mine_atk_min: number;
  mine_dfs_max: number;
  mine_dfs_min: number;
  wind_atk_max: number;
  wind_atk_min: number;
  wind_dfs_max: number;
  wind_dfs_min: number;
  water_atk_max: number;
  water_atk_min: number;
  water_dfs_max: number;
  water_dfs_min: number;
  fire_atk_max: number;
  fire_atk_min: number;
  fire_dfs_max: number;
  fire_dfs_min: number;
};
export const ATTR: AttrType = {
  life_max: 0,
  life: 0,
  mana_max: 0,
  mana: 0,
  atk_max: 0,
  atk_min: 0,
  dfs_max: 0,
  dfs_min: 0,
  hit: 0,
  dodge: 0,
  sudden: 0,
  ice_atk_max: 0,
  ice_atk_min: 0,
  ice_dfs_max: 0,
  ice_dfs_min: 0,
  mine_atk_max: 0,
  mine_atk_min: 0,
  mine_dfs_max: 0,
  mine_dfs_min: 0,
  wind_atk_max: 0,
  wind_atk_min: 0,
  wind_dfs_max: 0,
  wind_dfs_min: 0,
  water_atk_max: 0,
  water_atk_min: 0,
  water_dfs_max: 0,
  water_dfs_min: 0,
  fire_atk_max: 0,
  fire_atk_min: 0,
  fire_dfs_max: 0,
  fire_dfs_min: 0
};
