const { ART_TYPE } = require('./enum')
module.exports = {
    1: {
        id: 1,
        n: '封血咒',
        p: ART_TYPE.simple,
        d: 50,
        v: 150,
        up: 10,
        rp: 50,
        effect: 'torn_dfs_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成{v}%伤害,四转后无视目标{e}%防御。'
    },
    2: {
        id: 2,
        n: '七星咒',
        p: ART_TYPE.simple,
        d: 50,
        v: 150,
        up: 10,
        rp: 50,
        effect: 'torn_dfs_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成{v}%伤害,四转后无视目标{e}%防御。'
    },
    3: {
        id: 3,
        n: '噬魂斩',
        p: ART_TYPE.simple,
        d: 50,
        v: 150,
        up: 10,
        rp: 50,
        effect: 'torn_dfs_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成{v}%伤害,四转后无视目标{e}%防御。'
    },
    4: {
        id: 4,
        n: '破炎枪',
        p: ART_TYPE.simple,
        d: 50,
        v: 120,
        up: 8,
        rp: 40,
        effect: 'suck_life_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成{v}%伤害,四转后可恢复{e}%对目标造成伤害的生命。'
    },
    5: {
        id: 5,
        n: '断骨斧',
        p: ART_TYPE.simple,
        v: 120,
        up: 8,
        rp: 40,
        effect: 'suck_life_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成{v}%伤害,四转后可恢复{e}%对目标造成伤害的生命。'
    },
    6: {
        id: 6,
        n: '化血斩',
        p: ART_TYPE.simple,
        v: 120,
        up: 8,
        rp: 40,
        effect: 'suck_life_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成{v}%伤害,四转后可恢复{e}%对目标造成伤害的生命。'
    },
    7: {
        id: 7,
        n: '金光咒',
        p: ART_TYPE.simple,
        v: 120,
        up: 8,
        rp: 40,
        effect: 'injury_atk_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成&[v]&%伤害,四转后造成伤害+{e}%。',
    },
    8: {
        id: 8,
        n: '御剑术',
        p: ART_TYPE.simple,
        v: 120,
        up: 8,
        rp: 40,
        effect: 'injury_atk_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成&[v]&%伤害,四转后造成伤害+{e}%。',
    },
    9: {
        id: 9,
        n: '分影诀',
        p: ART_TYPE.simple,
        v: 120,
        up: 8,
        rp: 40,
        effect: 'injury_atk_ratio',
        effectValue: [10, 20, 30, 50],
        msg: '对单个目标造成&[v]&%伤害,四转后造成伤害+{e}%。',
    },
    10: {
        id: 10,
        n: '见血封喉',
        p: ART_TYPE.aoe,
        d: 100,
        v: 180,
        up: 7.4,
        rp: 40,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    11: {
        id: 11,
        n: '焚山煮海',
        p: ART_TYPE.aoe,
        d: 100,
        v: 180,
        up: 7.4,
        rp: 40,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    12: {
        id: 12,
        n: '万妖噬魂',
        p: ART_TYPE.aoe,
        d: 100,
        v: 180,
        up: 7.4,
        rp: 40,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    13: {
        id: 13,
        n: '力破千军',
        p: ART_TYPE.aoe,
        d: 100,
        v: 155,
        up: 7,
        rp: 35,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    14: {
        id: 14,
        n: '雷霆万钧',
        p: ART_TYPE.aoe,
        d: 100,
        v: 155,
        up: 7,
        rp: 35,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    15: {
        id: 15,
        n: '石破天惊',
        p: ART_TYPE.aoe,
        d: 100,
        v: 155,
        up: 7,
        rp: 35,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    16: {
        id: 16,
        n: '流光四溢',
        p: ART_TYPE.aoe,
        d: 100,
        v: 160,
        up: 7.3,
        rp: 30,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    17: {
        id: 17,
        n: '万剑归宗',
        p: ART_TYPE.aoe,
        d: 100,
        v: 160,
        up: 7.3,
        rp: 30,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    18: {
        id: 18,
        n: '移形换影',
        p: ART_TYPE.aoe,
        d: 100,
        v: 160,
        up: 7.3,
        rp: 30,
        t: 2,
        condition: 10,
        msg: '对{t}个目标目标造成{v}%伤害,四转后可增加攻击目标。'
    },
    19: {
        id: 19,
        n: '黄泉天怒',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'atk-100,sudden-20',
        msg: '战斗中临时提升{v}攻击与{v}暴击,持续{t}回合。'
    },
    20: {
        id: 20,
        n: '毁天灭地',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'atk-100,sudden-20',
        msg: '战斗中临时提升{v}攻击与{v}暴击,持续{t}回合。'
    },
    21: {
        id: 21,
        n: '血战八方',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'atk-100,sudden-20',
        msg: '战斗中临时提升{v}攻击与{v}暴击,持续{t}回合。'
    },
    22: {
        id: 22,
        n: '不动明王',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'life-1000,dfs-50',
        msg: '战斗中临时提升{v}生命与{v}防御,持续{t}回合。',
    },
    23: {
        id: 23,
        n: '斗转乾坤',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'life-1000,dfs-50',
        msg: '战斗中临时提升{v}生命与{v}防御,持续{t}回合。',
    },
    24: {
        id: 24,
        n: '金刚不灭',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'life-1000,dfs-50',
        msg: '战斗中临时提升{v}生命与{v}防御,持续{t}回合。',
    },
    25: {
        id: 25,
        n: '踏雪无痕',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'hit-20,dodge-20',
        msg: '战斗中临时提升{v}命中与{v}闪避,持续{t}回合。',
    },
    26: {
        id: 26,
        n: '追星逐月',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'hit-20,dodge-20',
        msg: '战斗中临时提升{v}命中与{v}闪避,持续{t}回合。',
    },
    27: {
        id: 27,
        n: '千里横行',
        p: ART_TYPE.buff,
        d: 200,
        t: 5,
        condition: 30,
        v: 'hit-20,dodge-20',
        msg: '战斗中临时提升{v}命中与{v}闪避,持续{t}回合。',
    },
    28: {
        id: 28,
        p: ART_TYPE.passive,
        n: '混元诀',
        v: 'life_max-1000',
        condition: 32,
        msg: '提升{v}生命上限。'
    },
    29: {
        id: 29,
        p: ART_TYPE.passive,
        n: '圣灵诀',
        v: 'mana_max-1000',
        condition: 34,
        msg: '提升{v}法力上限。'
    },
    30: {
        id: 30,
        p: ART_TYPE.passive,
        n: '黄泉咒',
        v: 'atk-50',
        condition: 36,
        msg: '提升{v}攻击上限。'
    },
    31: {
        id: 31,
        p: ART_TYPE.passive,
        n: '琉璃体',
        v: 'dfs-30',
        condition: 38,
        msg: '提升{v}防御上限。'
    },
    32: {
        id: 32,
        p: ART_TYPE.passive,
        n: '洞虚功',
        v: 'hit-10',
        condition: 40,
        msg: '提升{v}命中上限。'
    },
    33: {
        id: 33,
        p: ART_TYPE.passive,
        n: '寒江孤影',
        v: 'dodge-10',
        condition: 40,
        msg: '提升{v}闪避上限。'
    },
    34: {
        id: 34,
        p: ART_TYPE.passive,
        n: '五雷道法',
        v: 'sudden-10',
        condition: 40,
        msg: '提升{v}暴击上限。'
    },
    35: {
        id: 35,
        p: ART_TYPE.passive,
        n: '承天决',
        v: 'life_max-1000',
        condition: 32,
        msg: '提升{v}生命上限。'
    },
    36: {
        id: 36,
        p: ART_TYPE.passive,
        n: '乾坤诀',
        v: 'mana_max-1000',
        condition: 34,
        msg: '提升{v}法力上限。'
    },
    37: {
        id: 37,
        p: ART_TYPE.passive,
        n: '天罡咒',
        v: 'atk-50',
        condition: 36,
        msg: '提升{v}攻击上限。'
    },
    38: {
        id: 38,
        p: ART_TYPE.passive,
        n: '无极体',
        v: 'dfs-30',
        condition: 38,
        msg: '提升{v}防御上限。'
    },
    39: {
        id: 39,
        p: ART_TYPE.passive,
        n: '拈花功',
        v: 'hit-10',
        condition: 40,
        msg: '提升{v}命中上限。'
    },
    40: {
        id: 40,
        p: ART_TYPE.passive,
        n: '御风而行',
        v: 'dodge-10',
        condition: 40,
        msg: '提升{v}闪避上限。'
    },
    41: {
        id: 41,
        p: ART_TYPE.passive,
        n: '移山填海',
        v: 'sudden-10',
        condition: 40,
        msg: '提升{v}暴击上限。'
    },
    42: {
        id: 42,
        p: ART_TYPE.passive,
        n: '血泉决',
        v: 'life_max-1000',
        condition: 32,
        msg: '提升{v}生命上限。'
    },
    43: {
        id: 43,
        p: ART_TYPE.passive,
        n: '妖灵诀',
        v: 'mana_max-1000',
        condition: 34,
        msg: '提升{v}法力上限。'
    },
    44: {
        id: 44,
        p: ART_TYPE.passive,
        n: '妖煞咒',
        v: 'atk-50',
        condition: 36,
        msg: '提升{v}攻击上限。'
    },
    45: {
        id: 45,
        p: ART_TYPE.passive,
        n: '不灭体',
        v: 'dfs-30',
        condition: 38,
        msg: '提升{v}防御上限。'
    },
    46: {
        id: 46,
        p: ART_TYPE.passive,
        n: '玉虚功',
        v: 'hit-10',
        condition: 40,
        msg: '提升{v}命中上限。'
    },
    47: {
        id: 47,
        p: ART_TYPE.passive,
        n: '风驰电掣',
        v: 'dodge-10',
        condition: 40,
        msg: '提升{v}闪避上限。'
    },
    48: {
        id: 48,
        p: ART_TYPE.passive,
        n: '森罗万象',
        v: 'sudden-10',
        condition: 40,
        msg: '提升{v}暴击上限。'
    },
    49: {
        id: 49,
        p: ART_TYPE.passive,
        n: '狂血诀',
        v: 'life_max-1000',
        condition: 32,
        msg: '提升{v}生命上限。'
    },
    50: {
        id: 50,
        p: ART_TYPE.passive,
        n: '化灵诀',
        v: 'mana_max-1000',
        condition: 34,
        msg: '提升{v}法力上限。'
    },
    51: {
        id: 51,
        p: ART_TYPE.passive,
        n: '鬼神咒',
        v: 'atk-50',
        condition: 36,
        msg: '提升{v}攻击上限。'
    },
    52: {
        id: 52,
        p: ART_TYPE.passive,
        n: '混沌体',
        v: 'dfs-30',
        condition: 38,
        msg: '提升{v}防御上限。'
    },
    53: {
        id: 53,
        p: ART_TYPE.passive,
        n: '移花功',
        v: 'hit-10',
        condition: 40,
        msg: '提升{v}命中上限。'
    },
    54: {
        id: 54,
        p: ART_TYPE.passive,
        n: '扶摇而上',
        v: 'dodge-10',
        condition: 40,
        msg: '提升{v}闪避上限。'
    },
    55: {
        id: 55,
        p: ART_TYPE.passive,
        n: '无间地狱',
        v: 'sudden-10',
        condition: 40,
        msg: '提升{v}暴击上限。'
    },
    56: {
        id: 56,
        n: '青帝雷经',
        pet: true,
        p: ART_TYPE.simple,
        v: [100, 200, 300, 400, 500, 700, 1000],
        effect: 'torn_dfs_ratio',
        effectValue: [10, 20, 30, 40, 50, 70, 100],
        msg: '无视目标{e}%防御，对目标造成{v}%伤害。',
        noUp: true
    },
    57: {
        id: 57,
        n: '太白帝经',
        pet: true,
        p: ART_TYPE.simple,
        v: [100, 200, 300, 400, 500, 700, 1000],
        effect: 'injury_atk_ratio',
        effectValue: [10, 20, 30, 40, 50, 70, 100],
        msg: '对目标造成{v}%伤害,最终伤害额外+{e}%。',
        noUp: true
    },
    58: {
        id: 58,
        n: '玄武真怒',
        pet: true,
        p: ART_TYPE.simple,
        v: [100, 200, 300, 400, 500, 700, 1000],
        effect: 'add_atk_ratio',
        effectValue: [10, 20, 30, 40, 50, 70, 100],
        msg: '当前攻击提升{v}%，并对目标造成{v}%伤害。',
        noUp: true
    },
    59: {
        id: 59,
        n: '白虹贯日',
        pet: true,
        p: ART_TYPE.simple,
        v: [100, 200, 300, 400, 500, 700, 1000],
        msg: '对目标造成{v}%伤害。',
        noUp: true
    },
    60: {
        id: 60,
        p: ART_TYPE.fuTi,
        n: '附体',
        v: 10,
        condition: 10,
        msg: '可提升玩家生命上限,附加值为{v}%生命值。',
        maxL: 9
    },
} 